version: 0.0
os: linux
files:
  - source: /path/to/source/
    destination: /path/to/destination/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  AfterInstall:
    - location: scripts/start_app.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
