version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: Ronn4ValidateCode  # Replace with your Lambda function's name
        Alias: staging                  # Replace with the alias you want to deploy to
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  AfterInstall:
    - location: scripts/start_app.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
