version: 0.0
os: linux
files:
  - source: /app/index.html
    destination: /var/www/html/index.html
  - source: /app/app.py
    destination: /home/ubuntu/app.py

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
